spring:
  application:
    name: products-service
  datasource:
    url: jdbc:h2:mem:pos
    driverClassName: org.h2.Driver
    data: classpath:data.sql
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
